/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ActivityLogEntry = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'user' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const DepartmentHead = IDL.Record({
  'pin' : IDL.Text,
  'name' : IDL.Text,
  'departmentId' : IDL.Nat,
});
export const Department = IDL.Record({
  'id' : IDL.Nat,
  'icon' : IDL.Text,
  'color' : IDL.Text,
  'departmentLabel' : IDL.Text,
  'patientCount' : IDL.Nat,
});
export const ExternalForm = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'platform' : IDL.Text,
  'embedUrl' : IDL.Text,
  'departmentId' : IDL.Nat,
});
export const FormTemplate = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'fields' : IDL.Vec(IDL.Text),
  'departmentId' : IDL.Nat,
});
export const FieldValue = IDL.Record({
  'field' : IDL.Text,
  'value' : IDL.Text,
});
export const Report = IDL.Record({
  'id' : IDL.Nat,
  'fieldValues' : IDL.Vec(FieldValue),
  'submittedBy' : IDL.Text,
  'timestamp' : IDL.Int,
  'departmentId' : IDL.Nat,
});
export const SubmissionComment = IDL.Record({
  'author' : IDL.Text,
  'comment' : IDL.Text,
  'timestamp' : IDL.Int,
  'reportId' : IDL.Nat,
});
export const AppConfig = IDL.Record({
  'tvRefreshRate' : IDL.Nat,
  'departmentName' : IDL.Text,
  'hospitalName' : IDL.Text,
});
export const BackupData = IDL.Record({
  'departments' : IDL.Vec(Department),
  'formTemplates' : IDL.Vec(FormTemplate),
  'departmentHeads' : IDL.Vec(DepartmentHead),
  'externalForms' : IDL.Vec(ExternalForm),
  'reports' : IDL.Vec(Report),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const WaConfig = IDL.Record({
  'messageFormat' : IDL.Text,
  'accessToken' : IDL.Text,
  'phoneNumberId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addActivityLog' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearActivityLog' : IDL.Func([], [], []),
  'createDepartment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'createDepartmentHead' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'createExternalForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createFormTemplate' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'deleteDepartment' : IDL.Func([IDL.Nat], [], []),
  'deleteDepartmentHead' : IDL.Func([IDL.Text], [], []),
  'deleteExternalForm' : IDL.Func([IDL.Nat], [], []),
  'deleteFormTemplate' : IDL.Func([IDL.Nat], [], []),
  'getActivityLog' : IDL.Func([], [IDL.Vec(ActivityLogEntry)], ['query']),
  'getAllDepartmentHeads' : IDL.Func([], [IDL.Vec(DepartmentHead)], ['query']),
  'getAllDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
  'getAllExternalForms' : IDL.Func([], [IDL.Vec(ExternalForm)], ['query']),
  'getAllFormDeadlines' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
      ['query'],
    ),
  'getAllFormTemplates' : IDL.Func([], [IDL.Vec(FormTemplate)], ['query']),
  'getAllFormVersions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getAllReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getAllSubmissionComments' : IDL.Func(
      [],
      [IDL.Vec(SubmissionComment)],
      ['query'],
    ),
  'getAppConfig' : IDL.Func([], [IDL.Opt(AppConfig)], ['query']),
  'getBackupData' : IDL.Func([], [BackupData], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDepartment' : IDL.Func([IDL.Nat], [IDL.Opt(Department)], ['query']),
  'getDepartmentHead' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DepartmentHead)],
      ['query'],
    ),
  'getFormDeadline' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
  'getFormTemplate' : IDL.Func([IDL.Nat], [IDL.Opt(FormTemplate)], ['query']),
  'getFormVersion' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getReport' : IDL.Func([IDL.Nat], [IDL.Opt(Report)], ['query']),
  'getReportsByDepartment' : IDL.Func([IDL.Nat], [IDL.Vec(Report)], ['query']),
  'getSubmissionComment' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(SubmissionComment)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWaConfig' : IDL.Func([], [WaConfig], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFormDeadline' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAppConfig' : IDL.Func([AppConfig], [], []),
  'setFormDeadline' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'setSubmissionComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'setWaConfig' : IDL.Func([WaConfig], [], []),
  'submitReport' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(FieldValue)],
      [IDL.Nat],
      [],
    ),
  'updateDepartment' : IDL.Func([Department], [], []),
  'updateDepartmentHead' : IDL.Func([DepartmentHead], [], []),
  'updateExternalForm' : IDL.Func([ExternalForm], [], []),
  'updateFormTemplate' : IDL.Func([FormTemplate], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ActivityLogEntry = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'user' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const DepartmentHead = IDL.Record({
    'pin' : IDL.Text,
    'name' : IDL.Text,
    'departmentId' : IDL.Nat,
  });
  const Department = IDL.Record({
    'id' : IDL.Nat,
    'icon' : IDL.Text,
    'color' : IDL.Text,
    'departmentLabel' : IDL.Text,
    'patientCount' : IDL.Nat,
  });
  const ExternalForm = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'platform' : IDL.Text,
    'embedUrl' : IDL.Text,
    'departmentId' : IDL.Nat,
  });
  const FormTemplate = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'fields' : IDL.Vec(IDL.Text),
    'departmentId' : IDL.Nat,
  });
  const FieldValue = IDL.Record({ 'field' : IDL.Text, 'value' : IDL.Text });
  const Report = IDL.Record({
    'id' : IDL.Nat,
    'fieldValues' : IDL.Vec(FieldValue),
    'submittedBy' : IDL.Text,
    'timestamp' : IDL.Int,
    'departmentId' : IDL.Nat,
  });
  const SubmissionComment = IDL.Record({
    'author' : IDL.Text,
    'comment' : IDL.Text,
    'timestamp' : IDL.Int,
    'reportId' : IDL.Nat,
  });
  const AppConfig = IDL.Record({
    'tvRefreshRate' : IDL.Nat,
    'departmentName' : IDL.Text,
    'hospitalName' : IDL.Text,
  });
  const BackupData = IDL.Record({
    'departments' : IDL.Vec(Department),
    'formTemplates' : IDL.Vec(FormTemplate),
    'departmentHeads' : IDL.Vec(DepartmentHead),
    'externalForms' : IDL.Vec(ExternalForm),
    'reports' : IDL.Vec(Report),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const WaConfig = IDL.Record({
    'messageFormat' : IDL.Text,
    'accessToken' : IDL.Text,
    'phoneNumberId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addActivityLog' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearActivityLog' : IDL.Func([], [], []),
    'createDepartment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createDepartmentHead' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'createExternalForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createFormTemplate' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'deleteDepartment' : IDL.Func([IDL.Nat], [], []),
    'deleteDepartmentHead' : IDL.Func([IDL.Text], [], []),
    'deleteExternalForm' : IDL.Func([IDL.Nat], [], []),
    'deleteFormTemplate' : IDL.Func([IDL.Nat], [], []),
    'getActivityLog' : IDL.Func([], [IDL.Vec(ActivityLogEntry)], ['query']),
    'getAllDepartmentHeads' : IDL.Func(
        [],
        [IDL.Vec(DepartmentHead)],
        ['query'],
      ),
    'getAllDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
    'getAllExternalForms' : IDL.Func([], [IDL.Vec(ExternalForm)], ['query']),
    'getAllFormDeadlines' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
        ['query'],
      ),
    'getAllFormTemplates' : IDL.Func([], [IDL.Vec(FormTemplate)], ['query']),
    'getAllFormVersions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getAllReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getAllSubmissionComments' : IDL.Func(
        [],
        [IDL.Vec(SubmissionComment)],
        ['query'],
      ),
    'getAppConfig' : IDL.Func([], [IDL.Opt(AppConfig)], ['query']),
    'getBackupData' : IDL.Func([], [BackupData], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDepartment' : IDL.Func([IDL.Nat], [IDL.Opt(Department)], ['query']),
    'getDepartmentHead' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DepartmentHead)],
        ['query'],
      ),
    'getFormDeadline' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
    'getFormTemplate' : IDL.Func([IDL.Nat], [IDL.Opt(FormTemplate)], ['query']),
    'getFormVersion' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getReport' : IDL.Func([IDL.Nat], [IDL.Opt(Report)], ['query']),
    'getReportsByDepartment' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Report)],
        ['query'],
      ),
    'getSubmissionComment' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(SubmissionComment)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWaConfig' : IDL.Func([], [WaConfig], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFormDeadline' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAppConfig' : IDL.Func([AppConfig], [], []),
    'setFormDeadline' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'setSubmissionComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'setWaConfig' : IDL.Func([WaConfig], [], []),
    'submitReport' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(FieldValue)],
        [IDL.Nat],
        [],
      ),
    'updateDepartment' : IDL.Func([Department], [], []),
    'updateDepartmentHead' : IDL.Func([DepartmentHead], [], []),
    'updateExternalForm' : IDL.Func([ExternalForm], [], []),
    'updateFormTemplate' : IDL.Func([FormTemplate], [], []),
  });
};

export const init = ({ IDL }) => { return []; };