/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Department = IDL.Record({
  'id' : IDL.Nat,
  'icon' : IDL.Text,
  'color' : IDL.Text,
  'departmentLabel' : IDL.Text,
  'patientCount' : IDL.Nat,
});
export const FormTemplate = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'fields' : IDL.Vec(IDL.Text),
  'departmentId' : IDL.Nat,
});
export const FieldValue = IDL.Record({
  'field' : IDL.Text,
  'value' : IDL.Text,
});
export const Report = IDL.Record({
  'id' : IDL.Nat,
  'fieldValues' : IDL.Vec(FieldValue),
  'submittedBy' : IDL.Text,
  'timestamp' : IDL.Int,
  'departmentId' : IDL.Nat,
});
export const AppConfig = IDL.Record({
  'tvRefreshRate' : IDL.Nat,
  'departmentName' : IDL.Text,
  'hospitalName' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DepartmentHead = IDL.Record({
  'pin' : IDL.Text,
  'name' : IDL.Text,
  'departmentId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDepartment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'createDepartmentHead' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'createFormTemplate' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'deleteDepartment' : IDL.Func([IDL.Nat], [], []),
  'deleteDepartmentHead' : IDL.Func([IDL.Text], [], []),
  'deleteFormTemplate' : IDL.Func([IDL.Nat], [], []),
  'getAllDepartmentHeads' : IDL.Func([], [IDL.Vec(DepartmentHead)], ['query']),
  'getAllDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
  'getAllFormTemplates' : IDL.Func([], [IDL.Vec(FormTemplate)], ['query']),
  'getAllReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getAppConfig' : IDL.Func([], [IDL.Opt(AppConfig)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDepartment' : IDL.Func([IDL.Nat], [IDL.Opt(Department)], ['query']),
  'getDepartmentHead' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DepartmentHead)],
      ['query'],
    ),
  'getFormTemplate' : IDL.Func([IDL.Nat], [IDL.Opt(FormTemplate)], ['query']),
  'getReport' : IDL.Func([IDL.Nat], [IDL.Opt(Report)], ['query']),
  'getReportsByDepartment' : IDL.Func([IDL.Nat], [IDL.Vec(Report)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAppConfig' : IDL.Func([AppConfig], [], []),
  'submitReport' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(FieldValue)],
      [IDL.Nat],
      [],
    ),
  'updateDepartment' : IDL.Func([Department], [], []),
  'updateDepartmentHead' : IDL.Func([DepartmentHead], [], []),
  'updateFormTemplate' : IDL.Func([FormTemplate], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Department = IDL.Record({
    'id' : IDL.Nat,
    'icon' : IDL.Text,
    'color' : IDL.Text,
    'departmentLabel' : IDL.Text,
    'patientCount' : IDL.Nat,
  });
  const FormTemplate = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'fields' : IDL.Vec(IDL.Text),
    'departmentId' : IDL.Nat,
  });
  const FieldValue = IDL.Record({ 'field' : IDL.Text, 'value' : IDL.Text });
  const Report = IDL.Record({
    'id' : IDL.Nat,
    'fieldValues' : IDL.Vec(FieldValue),
    'submittedBy' : IDL.Text,
    'timestamp' : IDL.Int,
    'departmentId' : IDL.Nat,
  });
  const AppConfig = IDL.Record({
    'tvRefreshRate' : IDL.Nat,
    'departmentName' : IDL.Text,
    'hospitalName' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DepartmentHead = IDL.Record({
    'pin' : IDL.Text,
    'name' : IDL.Text,
    'departmentId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDepartment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createDepartmentHead' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'createFormTemplate' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'deleteDepartment' : IDL.Func([IDL.Nat], [], []),
    'deleteDepartmentHead' : IDL.Func([IDL.Text], [], []),
    'deleteFormTemplate' : IDL.Func([IDL.Nat], [], []),
    'getAllDepartmentHeads' : IDL.Func([], [IDL.Vec(DepartmentHead)], ['query']),
    'getAllDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
    'getAllFormTemplates' : IDL.Func([], [IDL.Vec(FormTemplate)], ['query']),
    'getAllReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getAppConfig' : IDL.Func([], [IDL.Opt(AppConfig)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDepartment' : IDL.Func([IDL.Nat], [IDL.Opt(Department)], ['query']),
    'getDepartmentHead' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DepartmentHead)],
        ['query'],
      ),
    'getFormTemplate' : IDL.Func([IDL.Nat], [IDL.Opt(FormTemplate)], ['query']),
    'getReport' : IDL.Func([IDL.Nat], [IDL.Opt(Report)], ['query']),
    'getReportsByDepartment' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Report)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAppConfig' : IDL.Func([AppConfig], [], []),
    'submitReport' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(FieldValue)],
        [IDL.Nat],
        [],
      ),
    'updateDepartment' : IDL.Func([Department], [], []),
    'updateDepartmentHead' : IDL.Func([DepartmentHead], [], []),
    'updateFormTemplate' : IDL.Func([FormTemplate], [], []),
  });
};

export const init = ({ IDL }) => { return []; };