/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppConfig {
  'tvRefreshRate' : bigint,
  'departmentName' : string,
  'hospitalName' : string,
}
export interface Department {
  'id' : bigint,
  'icon' : string,
  'color' : string,
  'departmentLabel' : string,
  'patientCount' : bigint,
}
export interface DepartmentHead {
  'pin' : string,
  'name' : string,
  'departmentId' : bigint,
}
export interface FieldValue { 'field' : string, 'value' : string }
export interface FormTemplate {
  'id' : bigint,
  'title' : string,
  'fields' : Array<string>,
  'departmentId' : bigint,
}
export interface Report {
  'id' : bigint,
  'fieldValues' : Array<FieldValue>,
  'submittedBy' : string,
  'timestamp' : bigint,
  'departmentId' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDepartment' : ActorMethod<[string, string, string], bigint>,
  'createDepartmentHead' : ActorMethod<[string, string, bigint], undefined>,
  'createFormTemplate' : ActorMethod<[bigint, string, Array<string>], bigint>,
  'deleteDepartment' : ActorMethod<[bigint], undefined>,
  'deleteDepartmentHead' : ActorMethod<[string], undefined>,
  'deleteFormTemplate' : ActorMethod<[bigint], undefined>,
  'getAllDepartmentHeads' : ActorMethod<[], Array<DepartmentHead>>,
  'getAllDepartments' : ActorMethod<[], Array<Department>>,
  'getAllFormTemplates' : ActorMethod<[], Array<FormTemplate>>,
  'getAllReports' : ActorMethod<[], Array<Report>>,
  'getAppConfig' : ActorMethod<[], [] | [AppConfig]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDepartment' : ActorMethod<[bigint], [] | [Department]>,
  'getDepartmentHead' : ActorMethod<[string], [] | [DepartmentHead]>,
  'getFormTemplate' : ActorMethod<[bigint], [] | [FormTemplate]>,
  'getReport' : ActorMethod<[bigint], [] | [Report]>,
  'getReportsByDepartment' : ActorMethod<[bigint], Array<Report>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAppConfig' : ActorMethod<[AppConfig], undefined>,
  'submitReport' : ActorMethod<[bigint, string, Array<FieldValue>], bigint>,
  'updateDepartment' : ActorMethod<[Department], undefined>,
  'updateDepartmentHead' : ActorMethod<[DepartmentHead], undefined>,
  'updateFormTemplate' : ActorMethod<[FormTemplate], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];